export interface BlockchainEvent {
  id: string;
  name: string;
  location: string;
  startDate: string; // YYYY-MM-DD
  endDate: string;   // YYYY-MM-DD
  color: string;
  url: string;
  emoji: string;
  description: string;
  tags: string[];
}

export const EVENTS: BlockchainEvent[] = [
  // March 2026
  {
    id: 'korea-blockchain-conf-2026',
    name: 'Korea Blockchain Conference',
    location: '서울, 대한민국',
    startDate: '2026-03-19',
    endDate: '2026-03-20',
    color: '#dc2626',
    url: 'https://koreablockchain.org',
    emoji: '🇰🇷',
    description: '국내 블록체인 산업의 최신 동향과 규제 변화를 다루는 국내 최대 블록체인 컨퍼런스. 정부 관계자, 기업, 스타트업이 한자리에.',
    tags: ['Blockchain', 'Korea', 'Regulation'],
  },
  {
    id: 'ethdenver-2026',
    name: 'ETHDenver',
    location: 'Denver, USA',
    startDate: '2026-03-04',
    endDate: '2026-03-09',
    color: '#8b5cf6',
    url: 'https://www.ethdenver.com',
    emoji: '🦄',
    description: '세계 최대 규모의 이더리움 해커톤 & 컨퍼런스. 개발자, 아티스트, 기업가들이 모여 Web3의 미래를 만들어갑니다.',
    tags: ['Ethereum', 'Web3', 'Hackathon'],
  },
  // April 2026
  {
    id: 'hk-web3-festival-2026',
    name: 'Hong Kong Web3 Festival',
    location: '홍콩',
    startDate: '2026-04-06',
    endDate: '2026-04-09',
    color: '#f59e0b',
    url: 'https://web3festival.org',
    emoji: '🐉',
    description: '아시아 최대 Web3 행사 중 하나. 홍콩의 디지털 자산 허브 전략 속에서 글로벌 업계 리더들이 한자리에 모입니다.',
    tags: ['Web3', 'DeFi', 'NFT', 'Asia'],
  },
  {
    id: 'token2049-dubai-2026',
    name: 'TOKEN2049 Dubai',
    location: '두바이, UAE',
    startDate: '2026-04-28',
    endDate: '2026-04-30',
    color: '#f7931a',
    url: 'https://www.token2049.com',
    emoji: '🏙️',
    description: '두바이에서 열리는 TOKEN2049. 전 세계 암호화폐 업계의 핵심 인물들이 모이는 최상위 프리미엄 네트워킹 행사.',
    tags: ['Crypto', 'Web3', 'Networking'],
  },
  // May 2026
  {
    id: 'consensus-2026',
    name: 'Consensus by CoinDesk',
    location: 'Austin, USA',
    startDate: '2026-05-11',
    endDate: '2026-05-14',
    color: '#06b6d4',
    url: 'https://consensus.coindesk.com',
    emoji: '🤝',
    description: 'CoinDesk 주관 세계 최대 블록체인 & 암호화폐 컨퍼런스. 정책, 투자, 기술 트렌드 전반을 다룹니다.',
    tags: ['Crypto', 'Blockchain', 'Policy'],
  },
  {
    id: 'web3-asia-sg-2026',
    name: 'Web3 Asia Summit',
    location: '싱가포르',
    startDate: '2026-05-20',
    endDate: '2026-05-21',
    color: '#10b981',
    url: 'https://web3asia.io',
    emoji: '🌏',
    description: '아시아 블록체인 스타트업과 투자자들을 연결하는 싱가포르 Web3 서밋. 동남아 Web3 생태계의 최신 트렌드를 한눈에.',
    tags: ['Web3', 'DeFi', 'Asia', 'Startup'],
  },
  // June 2026
  {
    id: 'superai-2026',
    name: 'SuperAI Singapore',
    location: '싱가포르',
    startDate: '2026-06-10',
    endDate: '2026-06-11',
    color: '#7c3aed',
    url: 'https://superai.com',
    emoji: '🤖',
    description: '싱가포르에서 열리는 아시아 최대 AI 컨퍼런스. AGI, 생성형 AI, AI×Blockchain 융합 트렌드를 탐구합니다.',
    tags: ['AI', 'Singapore', 'AGI'],
  },
  {
    id: 'ethglobal-tokyo-2026',
    name: 'ETHGlobal Tokyo',
    location: '도쿄, 일본',
    startDate: '2026-06-20',
    endDate: '2026-06-22',
    color: '#e11d48',
    url: 'https://ethglobal.com',
    emoji: '⛩️',
    description: '도쿄에서 열리는 이더리움 글로벌 해커톤. 일본 Web3 개발자 생태계의 가장 큰 축제로 48시간 논스톱 빌딩.',
    tags: ['Ethereum', 'Hackathon', 'Japan'],
  },
  // July 2026
  {
    id: 'asia-blockchain-summit-2026',
    name: 'Asia Blockchain Summit',
    location: '타이베이, 대만',
    startDate: '2026-07-14',
    endDate: '2026-07-16',
    color: '#0891b2',
    url: 'https://abs.io',
    emoji: '🗺️',
    description: '대만 타이베이에서 열리는 아시아 블록체인 서밋. 아시아 태평양 지역 블록체인 생태계의 핵심 연례 행사.',
    tags: ['Blockchain', 'Asia', 'DeFi'],
  },
  // August 2026
  {
    id: 'korea-blockchain-week-2026',
    name: 'Korea Blockchain Week',
    location: '서울, 대한민국',
    startDate: '2026-08-24',
    endDate: '2026-08-30',
    color: '#dc2626',
    url: 'https://koreablockchainweek.com',
    emoji: '🇰🇷',
    description: '서울에서 매년 열리는 코리아 블록체인 위크. BUIDL Asia, 해커톤, 각종 사이드 이벤트가 한 주 내내 이어집니다.',
    tags: ['Blockchain', 'Korea', 'DeFi', 'NFT'],
  },
  // September 2026
  {
    id: 'token2049-singapore-2026',
    name: 'TOKEN2049 Singapore',
    location: '싱가포르',
    startDate: '2026-09-17',
    endDate: '2026-09-18',
    color: '#f7931a',
    url: 'https://www.token2049.com',
    emoji: '🦁',
    description: '아시아 최대 암호화폐 컨퍼런스. 매년 1만 명 이상이 참여하며 Asia Crypto Week의 핵심 행사입니다. 놓치면 안 됩니다.',
    tags: ['Crypto', 'Web3', 'Singapore', 'Asia'],
  },
  {
    id: 'solana-breakpoint-2026',
    name: 'Solana Breakpoint',
    location: '싱가포르',
    startDate: '2026-09-19',
    endDate: '2026-09-21',
    color: '#9945ff',
    url: 'https://solana.com/breakpoint',
    emoji: '☀️',
    description: '솔라나 재단 공식 연례 컨퍼런스. 생태계 최신 소식, 신규 프로젝트 발표, 개발자 워크샵이 가득한 3일간의 축제.',
    tags: ['Solana', 'Web3', 'Singapore'],
  },
  {
    id: 'korea-ai-week-2026',
    name: 'Korea AI Week',
    location: '서울, 대한민국',
    startDate: '2026-09-28',
    endDate: '2026-09-30',
    color: '#0ea5e9',
    url: 'https://koreaaiweek.com',
    emoji: '🧠',
    description: '한국 AI 산업의 최신 동향을 총망라하는 국내 최대 AI 행사. AI×Blockchain 세션도 별도 운영됩니다.',
    tags: ['AI', 'Korea', 'Blockchain'],
  },
  // October 2026
  {
    id: 'devcon-2026',
    name: 'Devcon 8',
    location: '방콕, 태국',
    startDate: '2026-10-12',
    endDate: '2026-10-15',
    color: '#10b981',
    url: 'https://devcon.org',
    emoji: '🐘',
    description: '이더리움 재단 주관 최대 개발자 컨퍼런스. 방콕에서 개최되는 이번 Devcon은 아시아 이더리움 생태계 성장의 이정표.',
    tags: ['Ethereum', 'Developer', 'Thailand', 'Asia'],
  },
  {
    id: 'hk-fintech-week-2026',
    name: 'Hong Kong FinTech Week',
    location: '홍콩',
    startDate: '2026-10-26',
    endDate: '2026-10-30',
    color: '#0ea5e9',
    url: 'https://www.fintechweek.hk',
    emoji: '🏦',
    description: '홍콩 금융관리국(HKMA) 주관 글로벌 핀테크 행사. Web3, CBDC, 디지털 자산 규제를 중점적으로 다룹니다.',
    tags: ['FinTech', 'HongKong', 'Regulation', 'CBDC'],
  },
  // November 2026
  {
    id: 'sg-fintech-festival-2026',
    name: 'Singapore FinTech Festival',
    location: '싱가포르',
    startDate: '2026-11-11',
    endDate: '2026-11-13',
    color: '#16a34a',
    url: 'https://www.fintechfestival.sg',
    emoji: '🦉',
    description: '세계 최대 핀테크 행사. 싱가포르 금융통화청(MAS) 주관으로 60개국 6만 명 이상이 참여하는 연례 글로벌 페스티벌.',
    tags: ['FinTech', 'Singapore', 'DeFi', 'AI'],
  },
  {
    id: 'korea-fintech-week-2026',
    name: 'Korea FinTech Week',
    location: '서울, 대한민국',
    startDate: '2026-11-18',
    endDate: '2026-11-20',
    color: '#f59e0b',
    url: 'https://fintechweek.or.kr',
    emoji: '💳',
    description: '금융위원회 주관 국내 최대 핀테크 행사. 오픈뱅킹, CBDC, 블록체인 금융 등 최신 금융 혁신 동향을 공유합니다.',
    tags: ['FinTech', 'Korea', 'CBDC'],
  },
  // December 2026
  {
    id: 'japan-blockchain-conf-2026',
    name: 'Japan Blockchain Conference',
    location: '도쿄, 일본',
    startDate: '2026-12-03',
    endDate: '2026-12-04',
    color: '#ef4444',
    url: 'https://jbc.tokyo',
    emoji: '🗼',
    description: '일본 최대 블록체인 & 암호화폐 컨퍼런스. NFT, DeFi, Web3 게임 등 일본 특유의 크립토 문화가 풍성합니다.',
    tags: ['Blockchain', 'Japan', 'NFT', 'Gaming'],
  },
];
