export interface BlockchainEvent {
  id: string;
  name: string;
  location: string;
  startDate: string; // YYYY-MM-DD
  endDate: string;   // YYYY-MM-DD
  color: string;
  url: string;
  emoji: string;
  description: string;
  tags: string[];
  attendees: string;
  ticketPrice: string;
}

export const EVENTS: BlockchainEvent[] = [
  // ── February ───────────────────────────────────────────────────────────────
  {
    id: 'consensus-hongkong-2026',
    name: 'Consensus Hong Kong',
    location: '홍콩',
    startDate: '2026-02-10',
    endDate: '2026-02-12',
    color: '#0ea5e9',
    url: 'https://consensus-hongkong.coindesk.com/',
    emoji: '🐉',
    description: 'CoinDesk 주관 아시아 최대 블록체인 컨퍼런스. 홍콩컨벤션센터(HKCEC)에서 개최되며 기관 투자자, 규제 당국, 글로벌 Web3 리더 1만 5,000명 이상이 참여합니다.',
    tags: ['Crypto', 'Web3', 'Asia', 'HongKong', 'Institutional'],
    attendees: '15,000+',
    ticketPrice: 'Pro / Platinum 유료',
  },

  // ── April ──────────────────────────────────────────────────────────────────
  {
    id: 'hk-web3-festival-2026',
    name: 'Hong Kong Web3 Festival',
    location: '홍콩',
    startDate: '2026-04-20',
    endDate: '2026-04-23',
    color: '#f59e0b',
    url: 'https://www.web3festival.org/',
    emoji: '🏮',
    description: '완샹 블록체인랩 & HashKey Group 공동 주관. 390명 이상의 연사, 200개 이상의 전시 부스, 글로벌 Web3 기업이 집결하는 아시아 최대 Web3 행사. 홍콩 정부 지원 공식 행사.',
    tags: ['Web3', 'DeFi', 'NFT', 'HongKong', 'Asia'],
    attendees: '25,000~35,000',
    ticketPrice: '유료 (얼리버드 할인 가능)',
  },
  {
    id: 'bitcoin-conference-2026',
    name: 'Bitcoin Conference 2026',
    location: 'Las Vegas, USA',
    startDate: '2026-04-27',
    endDate: '2026-04-29',
    color: '#f7931a',
    url: 'https://2026.b.tc/',
    emoji: '₿',
    description: 'BTC Inc. 주관 세계 최대 비트코인 전문 컨퍼런스. The Venetian에서 개최되며 수만 명 규모의 비트코인 생태계 리더, 기관 투자자, 마이너들이 한자리에. 전년도 라인업: 마이크 노보그라츠, ETF 운용사 등.',
    tags: ['Bitcoin', 'Mining', 'Institutional'],
    attendees: '30,000+',
    ticketPrice: '$51 (GA) ~ $2,013 (Whale)',
  },
  {
    id: 'token2049-dubai-2026',
    name: 'TOKEN2049 Dubai',
    location: '두바이, UAE',
    startDate: '2026-04-29',
    endDate: '2026-04-30',
    color: '#e8a320',
    url: 'https://www.token2049.com/dubai',
    emoji: '🏙️',
    description: 'Madinat Jumeirah에서 열리는 전 세계 최상위 암호화폐 컨퍼런스. 160개국 1만 5,000명 이상 참여. TOKEN2049 Week(4/27~5/3) 전후로 수백 개의 사이드 이벤트가 열립니다.',
    tags: ['Crypto', 'Web3', 'Networking', 'DeFi'],
    attendees: '15,000+',
    ticketPrice: '$699 (얼리버드) ~ $5,999 (VIP)',
  },

  // ── May ────────────────────────────────────────────────────────────────────
  {
    id: 'consensus-miami-2026',
    name: 'Consensus 2026',
    location: 'Miami Beach, USA',
    startDate: '2026-05-05',
    endDate: '2026-05-07',
    color: '#06b6d4',
    url: 'https://consensus.coindesk.com/',
    emoji: '🌊',
    description: 'CoinDesk 주관 세계 최대 블록체인 컨퍼런스. Google, Microsoft, PayPal, Visa, BlackRock, Fidelity 등 글로벌 대기업이 스폰서. 100개국 2만 명 이상 참여. SEC 위원장 Paul Atkins, Brad Garlinghouse 등 기조연설.',
    tags: ['Crypto', 'Blockchain', 'Institutional', 'Policy'],
    attendees: '20,000+',
    ticketPrice: '유료 다중 티어 (Pro / Platinum)',
  },

  // ── June ───────────────────────────────────────────────────────────────────
  {
    id: 'superai-singapore-2026',
    name: 'SuperAI Singapore',
    location: '싱가포르',
    startDate: '2026-06-10',
    endDate: '2026-06-11',
    color: '#7c3aed',
    url: 'https://www.superai.com/',
    emoji: '🤖',
    description: 'Marina Bay Sands에서 열리는 아시아 최대 AI 컨퍼런스. 참가자 56%가 C레벨 임원. 발라지 스리니바산, 에드워드 스노든 등이 연사로 참여. AI × Blockchain 융합 세션 별도 운영.',
    tags: ['AI', 'AGI', 'Singapore', 'Asia'],
    attendees: '10,000+',
    ticketPrice: '$399 ~ $999',
  },

  // ── July ───────────────────────────────────────────────────────────────────
  {
    id: 'webx-tokyo-2026',
    name: 'WebX',
    location: '도쿄, 일본',
    startDate: '2026-07-13',
    endDate: '2026-07-14',
    color: '#e11d48',
    url: 'https://webx-asia.com/',
    emoji: '⛩️',
    description: '일본 최대 크립토 미디어 CoinPost 주관 아시아 최대 Web3 컨퍼런스. Prince Park Tower에서 개최, 170개 이상의 사이드 이벤트와 함께 진행. 일본 Web3 규제·생태계의 핵심 행사.',
    tags: ['Web3', 'Japan', 'NFT', 'Asia'],
    attendees: '14,000+',
    ticketPrice: '유료 (얼리버드 티어)',
  },

  // ── August ─────────────────────────────────────────────────────────────────
  {
    id: 'coinfest-asia-2026',
    name: 'Coinfest Asia',
    location: '발리, 인도네시아',
    startDate: '2026-08-20',
    endDate: '2026-08-21',
    color: '#10b981',
    url: 'https://coinfest.asia/',
    emoji: '🌴',
    description: 'Indonesia Crypto Network 주관. 90개국 1만 1,000명 이상이 참여하는 동남아 최대 블록체인 축제. 발리의 이국적인 환경에서 컨퍼런스·네트워킹·파티가 결합된 독특한 형식.',
    tags: ['Web3', 'Asia', 'DeFi', 'NFT', 'Community'],
    attendees: '11,000+',
    ticketPrice: '유료',
  },
  {
    id: 'bitcoin-asia-2026',
    name: 'Bitcoin Asia',
    location: '홍콩',
    startDate: '2026-08-27',
    endDate: '2026-08-28',
    color: '#f7931a',
    url: 'https://asia.b.tc/2026',
    emoji: '🦁',
    description: 'BTC Inc. 주관 아시아 플래그십 비트코인 컨퍼런스. 홍콩컨벤션센터에서 개최. Bitcoin Magazine의 아시아 거점 행사로 기관 투자자, 마이너, 개발자가 집결합니다.',
    tags: ['Bitcoin', 'HongKong', 'Asia', 'Institutional'],
    attendees: '대형',
    ticketPrice: '$48 (GA) ~ $1,888 (Whale)',
  },

  // ── September ──────────────────────────────────────────────────────────────
  {
    id: 'ethglobal-tokyo-2026',
    name: 'ETHGlobal Tokyo',
    location: '도쿄, 일본',
    startDate: '2026-09-25',
    endDate: '2026-09-27',
    color: '#4f46e5',
    url: 'https://ethglobal.com/events',
    emoji: '🔷',
    description: 'ETHGlobal 공식 주관 도쿄 해커톤. 전 세계 이더리움 개발자들이 48시간 논스톱으로 빌딩. 일본 Web3 개발자 생태계 최대 행사로, Ethereum Foundation 공식 후원.',
    tags: ['Ethereum', 'Hackathon', 'Japan', 'Developer'],
    attendees: '수백~2,000명',
    ticketPrice: '해커톤 참가 중심 (저렴)',
  },
  {
    id: 'korea-blockchain-week-2026',
    name: 'Korea Blockchain Week',
    location: '서울, 대한민국',
    startDate: '2026-09-29',
    endDate: '2026-10-01',
    color: '#dc2626',
    url: 'https://koreablockchainweek.com/',
    emoji: '🇰🇷',
    description: 'Upbit가 메인 스폰서, FactBlock 주관. 워커힐 호텔에서 개최되는 국내 최대 블록체인 행사. 2018년부터 이어온 연례 행사로 BUIDL Korea 등 수십 개 사이드 이벤트가 동시 진행됩니다.',
    tags: ['Blockchain', 'Korea', 'DeFi', 'Web3'],
    attendees: '수천 명',
    ticketPrice: '유료 (상세 추후 공개)',
  },

  // ── October ────────────────────────────────────────────────────────────────
  {
    id: 'token2049-singapore-2026',
    name: 'TOKEN2049 Singapore',
    location: '싱가포르',
    startDate: '2026-10-07',
    endDate: '2026-10-08',
    color: '#f7931a',
    url: 'https://www.token2049.com/singapore',
    emoji: '🦅',
    description: 'Marina Bay Sands 5개 층 전체를 사용하는 역대 최대 규모. 10,000명 이상이 매년 매진. Asia Crypto Week 핵심 행사. 아시아에서 가장 중요한 블록체인 네트워킹 이벤트입니다.',
    tags: ['Crypto', 'Web3', 'Singapore', 'Asia', 'DeFi'],
    attendees: '10,000+ (매진)',
    ticketPrice: '$399 (슈퍼 얼리버드) ~',
  },

  // ── November ───────────────────────────────────────────────────────────────
  {
    id: 'hk-fintech-week-2026',
    name: 'Hong Kong FinTech Week',
    location: '홍콩',
    startDate: '2026-11-02',
    endDate: '2026-11-06',
    color: '#0891b2',
    url: 'https://www.fintechweek.hk/',
    emoji: '🏦',
    description: 'InvestHK·HKMA 연계 공식 행사. 1,000명 이상의 연사, 800개 전시 부스, 45,000명 방문. CBDC, 디지털 자산 규제, Web3 금융을 중점적으로 다루는 아시아 최대 핀테크 행사.',
    tags: ['FinTech', 'HongKong', 'CBDC', 'Regulation', 'Asia'],
    attendees: '45,000+',
    ticketPrice: '유료 (사전 등록)',
  },
  {
    id: 'devcon-8-2026',
    name: 'Devcon 8',
    location: '뭄바이, 인도',
    startDate: '2026-11-03',
    endDate: '2026-11-06',
    color: '#10b981',
    url: 'https://devcon.org/',
    emoji: '🐘',
    description: 'Ethereum Foundation 주관 공식 최대 개발자 컨퍼런스. JIO World Center 뭄바이에서 개최 확정 (2025년 12월 이더리움 재단 공식 발표). 아시아 이더리움 생태계 성장의 이정표.',
    tags: ['Ethereum', 'Developer', 'India', 'Asia'],
    attendees: '5,000~15,000',
    ticketPrice: '유료 (추후 공개)',
  },
  {
    id: 'web-summit-2026',
    name: 'Web Summit',
    location: '리스본, 포르투갈',
    startDate: '2026-11-09',
    endDate: '2026-11-12',
    color: '#ff6600',
    url: 'https://websummit.com/',
    emoji: '🌐',
    description: '세계 최대 기술 컨퍼런스 중 하나. 70,000명 이상이 참여하며 AI, 블록체인, Web3 트랙 별도 운영. Google, Meta, Amazon, Microsoft 등 글로벌 빅테크 전원 참가.',
    tags: ['Tech', 'AI', 'Web3', 'Blockchain', 'Global'],
    attendees: '70,000+',
    ticketPrice: '유료 다중 티어',
  },
  {
    id: 'solana-breakpoint-2026',
    name: 'Solana Breakpoint',
    location: '런던, 영국',
    startDate: '2026-11-15',
    endDate: '2026-11-17',
    color: '#9945ff',
    url: 'https://solana.com/breakpoint',
    emoji: '☀️',
    description: 'Solana Foundation 공식 연례 컨퍼런스. Olympia Convention Centre 런던에서 개최 확정. 생태계 로드맵 발표, dApp 빌더 워크샵, 네트워킹 파티가 3일간 이어집니다.',
    tags: ['Solana', 'Web3', 'Developer', 'DeFi'],
    attendees: '수천 명',
    ticketPrice: '얼리버드 할인 가능',
  },
  {
    id: 'sg-fintech-festival-2026',
    name: 'Singapore FinTech Festival',
    location: '싱가포르',
    startDate: '2026-11-18',
    endDate: '2026-11-20',
    color: '#16a34a',
    url: 'https://www.fintechfestival.sg/',
    emoji: '🦉',
    description: 'MAS(싱가포르 금융통화청) 주관 세계 최대 핀테크 행사. Elevandi & Constellar 운영. 60개국 6만 명 이상이 참여하는 11회 연속 개최 행사. AI×금융, CBDC, 디지털 자산 트랙 포함.',
    tags: ['FinTech', 'Singapore', 'AI', 'CBDC', 'Asia'],
    attendees: '60,000+',
    ticketPrice: '유료 (다중 등록 옵션)',
  },

  // ── December ───────────────────────────────────────────────────────────────
  {
    id: 'blockchain-life-2026',
    name: 'Blockchain Life',
    location: '두바이, UAE',
    startDate: '2026-12-01',
    endDate: '2026-12-02',
    color: '#6366f1',
    url: 'https://blockchain-life.com/autumn2026/',
    emoji: '🌙',
    description: '17회째를 맞는 검증된 글로벌 블록체인 컨퍼런스. Dubai Festival Arena에서 130개국 1만 5,000명 이상 참여. 마이닝, 트레이딩, 거래소, DeFi 전문 세션 중심의 실전파 행사.',
    tags: ['Crypto', 'Mining', 'DeFi', 'Trading'],
    attendees: '15,000+',
    ticketPrice: '$189 (Standard) ~ VIP',
  },
];
